# Generated by Django 3.1.4 on 2021-01-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_inmueble_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='owner',
            new_name='user',
        ),
    ]
