# Generated by Django 3.1.4 on 2021-01-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20210106_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inmueble',
        ),
    ]
