# Generated by Django 3.1.4 on 2021-01-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_inmueble_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='biography',
            new_name='description',
        ),
    ]
