# Generated by Django 3.1.4 on 2021-01-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20210106_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
