# Generated by Django 3.1.4 on 2021-01-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20210106_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='bottom',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='front',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='surface',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
