# Generated by Django 3.1.4 on 2021-01-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20210106_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='uso_suelo',
            field=models.CharField(choices=[('PR', 'Privada'), ('EJ', 'Ejidal'), ('CM', 'Comunal')], default='AV', max_length=2),
        ),
    ]
