# Generated by Django 3.1.4 on 2021-01-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_inmueble_uso_suelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='uso_suelo',
            field=models.CharField(choices=[('RS', 'Residencial'), ('AP', 'Actividades Productivas'), ('EQ', 'Equipamiento'), ('IN', 'Infraestructura'), ('AV', 'Area Verde'), ('OT', 'Otro')], default='AV', max_length=2),
        ),
    ]
